package memory;

import br.unicamp.cogsys.core.entities.MemoryObjectType;

/**
 * @author klaus.raizer
 * @author andre.paraense
 * 
 * Types of memory object for world server 3d 
 *
 */
public enum MemoryObjectTypesWS3D implements MemoryObjectType
{
   /** memory objects generated by information*/
   RAW_AFFORDANCE,
   RAW_VISION,
   SELF_OBJECT,
   WORLD_OBJECT,
   TARGET_OBJECT,
   HAS_TARGET_OBJECT,
   SELF_NODE_POSITION,
   SPATIAL_NODE,
   ACTIVATION_LEVEL,
   HANDS_ACTION,
   TARGET_POS,
   MAP_GRID,
   CLOSEST_APPLE,
   ASTAR_NEXT_DESTINATION,
   RAW_INNER_SENSE,
   LEGS_ACTION,
   AFFORDANCE
   ;
}
